
SCU_DEFAULT_EV_CHG_TIME_SEC = (15 * 60)
SCU_DEFAULT_EV_CHG_AMOUNT_WH = (7 * 1000)
SCU_MAX_EV_CHG_TIME_SEC = (60 * 60)
SCU_MAX_EV_CHG_AMOUNT_WH = (30 * 1000)

SCU_MULT_POWER_WATT_TO_WATT_HOUR = 0.0002777777777777778  # 3600 s = 1 hour
SCU_MULT_MIN_TO_SEC = 60
SCU_MULT_KWH_TO_WH = 1000

SCU_STS_NONE = 0
SCU_STS_EV_CHARGER_IDLE = (SCU_STS_NONE + 1)
SCU_STS_EV_CHARGER_INITIALIZE = (SCU_STS_EV_CHARGER_IDLE + 1)
SCU_STS_EV_CHARGER_CABLE_CHECK = (SCU_STS_EV_CHARGER_INITIALIZE + 1)
SCU_STS_EV_CHARGER_CHARGING = (SCU_STS_EV_CHARGER_CABLE_CHECK + 1)
SCU_STS_EV_CHARGER_CHARGE_STOPPING = (SCU_STS_EV_CHARGER_CHARGING + 1)
SCU_STS_EV_CHARGER_CHARGE_ERROR = (SCU_STS_EV_CHARGER_CHARGE_STOPPING + 1)
SCU_STS_EV_CHARGER_CHARGE_TERMINATE = 10
SCU_STS_BAT_CHARGING_IDLE = 21
SCU_STS_BAT_CHARGING_INITIALIZE = (SCU_STS_BAT_CHARGING_IDLE + 1)
SCU_STS_BAT_CHARGING = (SCU_STS_BAT_CHARGING_INITIALIZE + 1)
SCU_STS_BAT_CHARGE_STOPPING = (SCU_STS_BAT_CHARGING + 1)
SCU_STS_BAT_CHARGE_ERROR = (SCU_STS_BAT_CHARGE_STOPPING + 1)
SCU_STS_BAT_CHARGE_COMPLETED = 30
SCU_STS_SHUTDN_KEY_LOCK_STILL_ON = 240

SCU_ST_IDLE = 0
SCU_ST_EV_CHG_WAIT = (SCU_ST_IDLE + 1)                          # 1
SCU_ST_EV_CHG_SBMS_RELAY_CLOSE = (SCU_ST_EV_CHG_WAIT + 1)       # 2
SCU_ST_EV_CHG_RUNNING = (SCU_ST_EV_CHG_SBMS_RELAY_CLOSE + 1)    # 3
SCU_ST_BAT_CHG_WAIT = (SCU_ST_EV_CHG_RUNNING + 1)               # 4
SCU_ST_BAT_CHG_RUNNING = (SCU_ST_BAT_CHG_WAIT + 1)              # 5
SCU_ST_STOPPING = (SCU_ST_BAT_CHG_RUNNING + 1)                  # 6
SCU_ST_STOPED = (SCU_ST_STOPPING + 1)
SCU_ST_DCDC_TEST_WAIT = (SCU_ST_STOPED + 1)
SCU_ST_DCDC_TEST = (SCU_ST_DCDC_TEST_WAIT + 1)
SCU_ST_DRIVE_WAIT = (SCU_ST_DCDC_TEST + 1)
SCU_ST_DRIVING = (SCU_ST_DRIVE_WAIT + 1)
SCU_ST_ERROR = (SCU_ST_DRIVING + 1)
SCU_ST_SHUTDOWN = (SCU_ST_ERROR + 1)
SCU_ST_BOOT = (SCU_ST_SHUTDOWN + 1)
SCU_ST_EMERGENCY_STOP = (SCU_ST_BOOT + 1)
SCU_ST_ADMIN = (SCU_ST_EMERGENCY_STOP + 1)
SCU_ST_END = (SCU_ST_ADMIN + 1)

SCU_SUB_ST_EV_IDLE = 0
SCU_SUB_ST_EV_START = (SCU_SUB_ST_EV_IDLE + 1)
SCU_SUB_ST_EV_RUN_WAIT = (SCU_SUB_ST_EV_START + 1)
SCU_SUB_ST_EV_RUN = (SCU_SUB_ST_EV_RUN_WAIT + 1)
SCU_SUB_ST_EV_STOP = (SCU_SUB_ST_EV_RUN + 1)
SCU_SUB_ST_EV_END = (SCU_SUB_ST_EV_STOP + 1)

SCU_SUB_ST_BAT_IDLE = 0
SCU_SUB_ST_BAT_START = (SCU_SUB_ST_BAT_IDLE + 1)
SCU_SUB_ST_BAT_RUN_WAIT = (SCU_SUB_ST_BAT_START + 1)
SCU_SUB_ST_BAT_RUN = (SCU_SUB_ST_BAT_RUN_WAIT + 1)
SCU_SUB_ST_BAT_STOP = (SCU_SUB_ST_BAT_RUN + 1)
SCU_SUB_ST_BAT_END = (SCU_SUB_ST_BAT_STOP + 1)

SCU_SUB_ST_TM_IDLE = 0
SCU_SUB_ST_TM_DIRECT = (SCU_SUB_ST_TM_IDLE + 1)   # DCDC MODULE DIRECT CONTROL
SCU_SUB_ST_TM_END = (SCU_SUB_ST_TM_DIRECT + 1)

SCU_SUB_ST_AM_IDLE = 0
SCU_SUB_ST_AM_SET_TIMESTEMP = (SCU_SUB_ST_AM_IDLE + 1)    # SET SECC's TIMESTEMP
SCU_SUB_ST_AM_END = (SCU_SUB_ST_AM_SET_TIMESTEMP + 1)

SCU_CHG_MODE_NONE = 0
SCU_CHG_MODE_TIME = (SCU_CHG_MODE_NONE + 1)
SCU_CHG_MODE_AMOUNT = (SCU_CHG_MODE_TIME + 1)
SCU_CHG_MODE_END = (SCU_CHG_MODE_AMOUNT + 1)

SCU_CHG_CTRL_NONE = 0
SCU_CHG_CTRL_START_CHG = (SCU_CHG_CTRL_NONE + 1)
SCU_CHG_CTRL_STOP_CHG = (SCU_CHG_CTRL_START_CHG + 1)
SCU_CHG_CTRL_END = (SCU_CHG_CTRL_STOP_CHG + 1)


class SCU_Param:
    def __init__(self):
        self.state = 0
        self.sub_state = 0
        self.ev_led_status = 0
        self.bat_led_status = 0
        self.stop_led_status = 0
        self.drive_led_status = 0
        self.ev_chg_mode = 0
        self.ev_chg_time_sec = 0
        self.ev_chg_amount_wh = 0
        self.bat_chg_control = 0
        self.retry_count = 0
        self.timestamp = 0
        self.charging_amount_wh = float(0)
